camel-tooling/vscode-camelk

package.json, src/extension.ts
The child process handle is stored in the workspace state (might not be so safe between editor restarts), so when run with `kamel --dev` sending `CTRL+C` (`SIGINT`) will stop/delete the running kamel integration.
Otherwise if the kamel integration is run outside of the workspace it will be stopped/deleted via `kamel delete`.
Super POCy :)
=> chore: add simple stop command

CHANGELOG.md, src/CamelKJSONUtils.ts
it introduced a regression to use the Start integration command palette
also, if a user has hidden or closed the output panel, he/she doesn't
want to have the output popping on each information/trace message
=> Avoid showing output on each message #106

CHANGELOG.md, package.json
fixes #112
I didn't find a simple way of implementing an automated way of testing this, so I tested manually against a local cluster and it works nicely.
=> Add support for starting integrations with YAML file extension

CHANGELOG.md, package-lock.json, package.json, src/JavaDependenciesManager.ts, src/extension.ts
files
- the Camel K files requires to contain "camel" inside it (same
constraint to have Camel URI support)
- currently providing dependencies only from camel-core-engine. Camel K
can pull some other dependencies but needs some work on kamel inspect to
leverage that
- not smart dependencies declaration all artifacts are hardcoded which
will make it hard to maintain on the long-run but should be fine for a
first iteration
/!\ it requires vscode-java 0.55.0 https://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D (planned to be released on the 23rd December)
will need to think mor eon it but I think that the best to test it is to write a UI test checking for completion. I will surely delegate to QE in this case.
=> FUSETOOLS2-81 - support pure Java language with standalone Camel K Java

src/JavaDependenciesManager.ts
before it was supporting only direct list of pattern to jars, now
support also when specified using include/exclude properties
tests will be covered with UI tests written by QE
fo rinstance if usingin settings.json:
```
{
"java.project.referencedLibraries": {
"include" :[
"library/**/*.jar",
"/home/username/lib/foo.jar"
], "exclude": []
}
}
```
it will now work
see https://issues.redhat.com/browse/FUSETOOLS2-81?focusedCommentId=13940317&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13940317
=> FUSETOOLS2-81 - support complex java.project.referencedLibraries

src/test/suite/completion.java.test.ts
to unblock situation and still keep the test on Travis at least.
=> FUSETOOLS2-207 - skip java completion test on Jenkins

src/extension.ts, src/test/suite/kubectlwatcher.test.ts
available
- start/stop kubectl watch depending if the Apache Camel K view is
visible or not
TODO:
- validate that this watch is used only for Apache Camel K view --> Edit: validated that it is
- write a test --> Edit: test provided
For Future:
- there might a nicer way to handle the running kubectl watch process:
have delay between relaunch in case of timeout, avoid mix of event to
start and direct access to stop
note there is still an infinite loop when teh Apache Camel K view is opened (but at least there is a workaround now and it won't be the default)
=> FUSETOOLS2-205 - avoid infinite loop when no Kubernetes instance

CHANGELOG.md, src/CamelKNodeProvider.ts, src/extension.ts, src/test/suite/kubectlwatcher.test.ts
when cannot reach connection and Apache camel k integration Tree view is
opened
no test, seems VS Code TreeView is missing APIs to programmatically open
an empty TreeView... and after few hours for searchign still cannot manage to find a workaround, see also  https://stackoverflow.com/questions/59983711/how-to-programmatically-make-a-treeview-visible?noredirect=1#comment106081291_59983711
=> FUSETOOLS2-205 - avoid infinite loop

CHANGELOG.md, README.md, package.json, src/CamelKTaskDefinition.ts, src/IntegrationUtils.ts, src/extension.ts, src/test/suite/CamelKTaskDefinition.test.ts
- Task metamodel for most of the kamel attributes possible
- default task to launch indev mode
- using a ShellExecution to allow user to check the command used and the
output of it
improvements possibilities which I think can be handled in another iteration:
- more precise model definition for attributes having a <key>=<value>
list such as properties, environment variables (but need to find how to
specify that in the package.json...)
- improve completion for values of each attributes. Either using a
specific VS Code completion provider, or Language Server for tasks.json
files or defining more in package.json if it is possible (but it won't
be dynamic in that case)
- auto-generate metamodel based on kamel definition (but seems a really
hard task)
- use full kamel path if kamel not …
=> FUSETOOLS2-215 - Provide Task to launch Camel K Integration

src/extension.ts, src/kubectlutils.ts, src/logsWebview.ts
=> issue #311 - shifting to kamel log instead of kubectl log

src/test/suite/completion.tasks.test.ts
we already deactivated the test for completion for Java files when
running on Jenkins for VS Code Camel K files.
I guess the easiest for now is deactivate this one too as it is playing
correctly locally and on Travis and already spent a fair amount of time
investigating without success.
=> FUSETOOLS2-259 - Skip completion test on Jenkins

package.json
see doc https://code.visualstudio.com/api/references/contribution-points#Sorting-of-groups
=> FUSETOOLS2-235 - provide divider in context menu

CHANGELOG.md, src/task/CamelKTaskCompletionItemProvider.ts, src/task/TraitManager.ts, src/test/suite/CamelKTaskCompletionItemProvider.test.ts, src/test/suite/Utils.ts, src/test/suite/completion.tasks.test.ts, src/test/suite/install.test.ts, testFixture/tasks.json
trait completion limited to trait name outside of quotes
possible improvements:
- cache Kamel trait list until the kamel cli is updated
- support inside ""
- completion (filtered) when there is a beginning of value typed inside
""
- autocompletes for trait parameter and default values
=> FUSETOOLS2-229 - provide initial trait completion

Contributing.md, src/installer.ts, src/test/suite/install.test.ts, src/versionUtils.ts
- the cache needs a restart of VS Code to be updated
- given that the version is modified no more than once a month, I don't
think that it is a problem
- the idea is also to avoid 403 rate limit exceeded when playing tests
on CIs
=> FUSETOOLS2-305 use cache for latest Camel version available

src/test/suite/CamelKTaskCompletionItemProvider.test.ts
currently test failing on Jenkins CI with timeout, the method called
waiting for activation had an higher timeout than the test itself.
=> FUSETOOLS2-354 - increase timeout for completion test

CHANGELOG.md, README.md, package-lock.json, package.json, src/commands/NewIntegrationFileCommand.ts, src/extension.ts, src/test/suite/commands/NewIntegrationFileCommand.test.ts, src/test/suite/commands/NewIntegrationFileCommandValidation.test.ts
- requires a root folder
- can be created only at the root
- only create the file, doesn't open it due to issues with kamel.exec
not returning. So will be improved in another iteration, see https://issues.redhat.com/browse/FUSETOOLS2-303
please note that a kubeconfigf needs to be available currently, see [here](https://github.com/apache/camel-k/issues/1368)
Potential error on creation are not reported but it is linked to the problem of kamel.exec
=> FUSETOOLS2-139 - Command to create a new Apache Camel K integration file

src/task/CamelKTaskCompletionItemProvider.ts, src/task/TraitDefinition.ts, src/task/TraitManager.ts, src/task/TraitProperty.ts, src/test/suite/CamelKTaskCompletionItemProvider.test.ts
recommending to compare using ignore whitespace, I updated the spaces issue. (if it is a problem i can create a different PR)
not added items to changelog as I think it can stay in the generic "completion for trait names in tasks.json" already available
=> FUSETOOLS2-356 - provide trait properties when choosing trait

src/test/suite/commands/NewIntegrationFileCommand.test.ts
as it requires a valid kubeconfig setup
=> FUSETOOLS2-358 - skip New File test on Jenkins

src/test/suite/Utils.ts, src/test/suite/extension.test.ts
case of failures
it seems to do the trick:
on 6 builds launched on Jenkins all of them are in success for the initially incriminated tests. 1 has a failing test but this would be another flaky tests due to other reasons.
as it is flaky we cannot be sure, so I think that keeping the trace in console log in test execution is better.
see builds 19 to 24 https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/VS%20Code/job/vscode-camelk-release-temporary-testing/
=> FUSETOOLS2-411 - rework conditional wait and try to have more details in

CHANGELOG.md, src/task/CamelKTaskCompletionItemProvider.ts, src/task/TraitManager.ts, src/test/suite/CamelKTaskCompletionItemProvider.test.ts, src/test/suite/completion.tasks.test.ts, testFixture/tasks.json
- range needs to be dummy specified otherwise VS Code framework is
filtering completion out for some reasons (see
https://github.com/microsoft/vscode/issues/95449#issuecomment-621896285
)
- prefix is required to have completions appearing before the long list
of defaults variables in tasks.json context
for next iterations:
- provide default value of property https://issues.redhat.com/browse/FUSETOOLS2-419
- provide snippet with a list of potential value for the property in case of enums https://issues.redhat.com/browse/FUSETOOLS2-420
a non-regression tes for the whole use case, needs ot beprovided at UI level due to mentioned VS Code behavior https://github.com/microsoft/vscode/issues/95449#issuecomment-621896285 , created https://issues.redhat.com/browse/FUSETOOLS2-418
=> FUSETOOLS2-290 - provide completion for trait properties

src/IntegrationUtils.ts, src/test/suite/IntegrationUtils.test.ts
Apache Camel Integration" list
it is currently logging an error in the VS Code Camel K output. Not sure
that it is needed but it is coherent with the other cases of the "Start
Apache Camel Integration" command when an "escape" is called in one of
the inputbox
=> FUSETOOLS2-311 - fix issue when calling "escape" on task list of "Start

src/commands/NewIntegrationFileCommand.ts, src/kamel.ts, src/test/suite/_completion/completion.java.test.ts, src/test/suite/_completion/completion.tasks.test.ts, src/test/suite/commands/NewIntegrationFileCommand.test.ts
note: updated the kamel invoke method to resolve promise on 'close'
event. Otherwise the Promise was never resolved even if the command
ended.
--> not modified changelog as I don't think it is worthy to add a specific line for it given that the new command to create Integration file is already provided
=> FUSETOOLS2-303 - open created file in editor

didact/camelk/first-integration.md
- VS Code is providing a command which is more straightforward
- it will avoid to have to maintain the code to copy
- it simplifies the tutorial by providing a single optimal path to work
instead of 2 different paths.
=> FUSETOOLS2-476 - remove non optimal information to copy-paste code

src/kamel.ts
correct
would be better if underlying kamel/kubectl provides more precise
message but I think they are targeting users with different set of
skills and it will require a lot more work to include it upstream. So as
a first iteration,
here is this not very nice but  improving slightly UX for users.
testing it would require quite a lot of refactor and mock. Not sure if
it is worthy.
If the approach seems fine, we can discuss to take time to write the test or not. i wanted to share this kind of modification before investing any time on the testing because even if improving UX slightly, it is really ugly. But I don't have a better idea on short term.
=> FUSETOOLS2-4 - improve message error when Camel K installation not

.travis.yml, CHANGELOG.md, configure-minikube-camelk.md, src/JavaDependenciesManager.ts, src/kamel.ts, src/task/TraitManager.ts, src/test/suite/CamelKTaskCompletionItemProvider.test.ts, src/versionUtils.ts
- update the default value
- update last version time
- provide a workaround for bug
https://github.com/apache/camel-k/issues/1511 . it includes a "sanitize"
of the retrieved string by removing the extra yaml returned. given that
the size of the returned string is higher than 65536, the output is send
in 2 chunks, which requires to improve the kamel command call in our
codde
- update number of traits available in traits
=> FUSETOOLS2-487 - upgrade default kamel from 1.0.0-RC2 to 1.0.0

Jenkinsfile, src/CamelKJSONUtils.ts, src/JavaDependenciesManager.ts, src/extension.ts, src/test/suite/Utils.ts, src/test/suite/_completion/completion.java.test.ts, src/test/suite/camelkjsonutils.test.ts, src/test/suite/helloworld.groovy, src/test/suite/integrationExplorer.test.ts, src/test/suite/kubectlwatcher.test.ts
- use rhel8 insteadof rhel 7 to workaround https://github.com/microsoft/vscode/issues/99492
- use extension API to be able to reach variables used in tests
- deactivate 2 tests in kubectlwatcher that requires too much work of using Object oriented programmation (without insurance that it be enough)
=> FUSETOOLS2-490 - fix master

src/test/suite/_completion/completion.java.test.ts
after rework of the test fo r1.0.0, seems we can now reactivate the test on Jenkins
https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/VS%20Code/job/vscode-temporary-testing/49/console
```
Should do completion in Camel K standalone files
✓ Completes from method for Java: 12590ms
```
=> FUSETOOLS2-207 - reactivate Java completion tests on Jenkins

package.json, src/config.ts, src/extension.ts, src/test/suite/versionUtils.test.ts, src/versionUtils.ts
=> fixed broken camelK version check due to new tag naming logic #500

src/ui-test/camelk_extension_test.ts
Temporary solution until FUSETOOLS2-589 is resolved.
Signed-off-by: Marian Lorinc <mlorinc@redhat.com>
=> FUSETOOLS2-599 - Fix failing ui-tests after vscode 1.48.0 update

Jenkinsfile
as it is required now for VS Code java and so Ui tests
=> FUSETOOLS2-604 - Upgrade Java on Jenkins to Java 11

src/test/suite/_completion/completion.yaml.test.ts
it avoids failure on Jenkins
in build https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/VS%20Code/job/vscode-temporary-testing/65/console we can notice that the test are well skipped. The buidl is failign due to unrelated error with erro fetchign kamel utility
=> FUSETOOLS2-625 - variable cannot be reused for test skipping in Mocha

.travis.yml, CHANGELOG.md, package.json, src/JavaDependenciesManager.ts, src/test/suite/versionUtils.test.ts, src/versionUtils.ts
The fix consists in upgrading the default version.
I created https://issues.redhat.com/browse/FUSETOOLS2-713 to try to avoid breaking the master.
I created https://github.com/camel-tooling/vscode-camelk/pull/552 to have a clearer error message at least
we can notice that the test is passing https://travis-ci.org/github/camel-tooling/vscode-camelk/builds/729237598#L968 This is checked via separate temporary branch/[PR](https://github.com/camel-tooling/vscode-camelk/pull/556) because the test requires to have access to github token.
=> FUSETOOLS2-709 - fix broken master after Camel K 1.1.1 release

.travis.yml, Jenkinsfile
it allows to ensure that the package-lock.json is respected
=> FUSETOOLS2-701 - use npm ci instead of npm install

src/task/CamelKTaskDefinition.ts
- create folder with a space in path
- create an Integration file in this folder
- Call command "Start Integration"
- choose "task"
- choose the default one called "Start in dev mode Camel K integration opened in active editor"
test covering this use case provided in this PR https://github.com/camel-tooling/vscode-camelk/pull/571
=> FUSETOOLS2-754 - support space in path for default provided task

src/task/CamelKTaskDefinition.ts, src/test/suite/CamelKTaskDefinition.test.ts
test covering this use case provided in this PR https://github.com/camel-tooling/vscode-camelk/pull/571
=> FUSETOOLS2-222 - support task also when kamel is not on user path

.travis.yml, package.json, src/test/suite/CamelKTaskCompletionItemProvider.test.ts, src/test/suite/versionUtils.test.ts, src/versionUtils.ts
nota: the version of Camel dependencies is still the same 3.5.0
https://github.com/apache/camel-k-runtime/blob/f52b4c4e37ef9c6c3f5ad3b3929e220f7fe63b12/pom.xml#L41
=> FUSETOOLS2-780 - upgrade default version to Camel K 1.2.0

CHANGELOG.md, src/config.ts, src/kamel.ts, src/kubectl.ts, src/test/suite/kamel.test.ts, src/test/suite/kubectl.test.ts
nota: given that the current bad behavior is that binary on system path
takes precedence over manually specified tool path, the tests require to
not have set the kamel and kubectl on system path. It also requires to
be launched on Linux as binaries are provided for linux only fo rthe
test.
=> FUSETOOLS2-813 - support space to path of executable kamel and kubectl

package.json, src/CamelKSchemaManager.ts
we were pointing to master as it was implemented when there was no tag
available yet. it was refactored on master. So pointing to latest tag.
It will avoid breakage from external part but requires more maintenance.
including more traces in log too for next time, it will be easier to
debug (see https://travis-ci.com/github/camel-tooling/vscode-camelk/builds/202096761#L391 for instance)
=> FUSETOOLS2-878 - update link to Camel K schema

.circleci/config.yml, sonar-project.properties, src/test/suite/StartIntegration.test.ts
- use image to have a privileged Docker access required by minikube.
Using the docker vm-driver which is the only one which seems to work
(available in latest minikube)
- increase timeout for one test as it is takingmore time on Circle CI
- some artifacts are uploaded: it is log of VS Code and the VS Code User
Storage. Useful for debugging
- steps ordered to compile before installing requirements for test that
are taking a long time
=> FUSETOOLS2-857 - Add Circle CI config

.circleci/config.yml
it allows to simplify the installation
=> FUSETOOLS2-857 - use .deb for minikube installation

.circleci/config.yml, .travis.yml, CHANGELOG.md, package.json, src/test/suite/versionUtils.test.ts, src/versionUtils.ts
Note: the Camel version is still the same
https://github.com/apache/camel-k-runtime/blob/f52b4c4e37ef9c6c3f5ad3b3929e220f7fe63b12/pom.xml#L41
=> FUSETOOLS2-892 - update default from kamel 1.2.0 to 1.2.1

.circleci/config.yml, CHANGELOG.md, package.json
2 PRS are mandatory due to 2 external problems that break the master, grouping the 2 inthis PR to have a green build:
https://github.com/camel-tooling/vscode-camelk/pull/652
https://github.com/camel-tooling/vscode-camelk/pull/650
Having the 2 other PRs can ease review of the ùmodifications but I think that th emerge need to be doen from this one
=> Mandatory PRs to fix master

.circleci/config.yml, CHANGELOG.md, package.json, src/JavaDependenciesManager.ts, src/test/suite/CamelKTaskCompletionItemProvider.test.ts, src/test/suite/versionUtils.test.ts, src/versionUtils.ts
- not updated the versionUtil.LAST_MODIFIED_DATE_OF_DEFAULT_VERSION
because the release is missing on github
https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/Missing.201.2E3.2E0.20release.20on.20Github/near/221051887
- support of new features such as debug and local deployment command to
be added in a separated PR
=> FUSETOOLS2-929 - upgrade to Camel K 1.3.1

sonar-project.properties
it will avoid to have it listed as non-covered https://sonarcloud.io/component_measures?id=vscode-camelk&metric=coverage&view=list
=> add ui-test in list of sonar.tests

CHANGELOG.md, USAGE_DATA.md, src/ConfigMapAndSecrets.ts, src/Telemetry.ts, src/extension.ts
- there is no existing test at top level of commands call. I have not
found how
to add an assertion without high complexity
- it is covering only "happy" case. In case of failure, no telemetry
reported in most case. In case of abortion of the command, a telemetry
event is reported without mentioning that user didn't go to the end of
the "wizard command"
https://snapshot.woopra.com/5GeHozdVXv4ujHQiSgQLcHBerREYPXSpGkCqLoJkd5rBWPKq3qjREgUCrjqDCdDqR3
=> FUSETOOLS-1035 - provide basic telemetry for most commands

.vscodeignore
especially the test fixture which are taking hundreds of Mo
uncompressed, around 30 Mo compressed in the vsix
=> FUSETOOLS2-1044 - remove several useless artifacts from vsix

src/JavaDependenciesManager.ts, src/extension.ts
https://drive.google.com/file/d/1ukRoit7eG1DqxE4NiJO2DC4js8XTRBRa/view?usp=sharing
it allows to have compilation classpath well detected when isntalling VS
Code Camel K extension and that the Java Camel K file is already open.
as it is a complicated use case to test (need to uninstall extension
under test, clean settings folder or restart vs code and then reinstall
it), I do not know how it can be easily automated at the level we have
setup the test infrastructure.
for the future, might be nice to have a feedback to the user on the
progress of the downloads so that he/she knows that the "current
compilation" error should vanish soon. But my last attempt to have
feedback progress from Maven launched through node was a failure.
=> FUSETOOLS2-1043 - update compilation classpath when ready

README.md
=> Update badge for chat that ha moved from Gitter to Zulip

CHANGELOG.md, README.md, package.json, resources/maven-project/pom-to-copy-java-dependencies.xml, src/JavaDependenciesManager.ts, src/extension.ts, src/test/suite/_completion/completion.java.test.ts, test Fixture with speci@l chars/MyRouteBuilderWithAdditionalDependencies.java
demo video here https://youtu.be/C2gKvnmSYVA
requires upgrade to Camel K 1.4.0
provide command to add dependencies on classpath.
no test to handle 1.3- as this use case is considered as best effort
only.
for next iterations:
- automatically call refresh when needed (to be determined when it is
needed)
- use a specific folder per file
- find a way to support two files opened at same time in different
window which are not sharing the same dependencies
- allow to configure parameters to provide to the call (like a maven
repository)
- provide progress report of refresh
limitations due to upstream:
- some notations not supported
https://github.com/apache/camel-k/issues/2213
- a lot of place is taken in internal folders as jars are duplicated
instead of simply pointing to local .m2 …
=> FUSETOOLS2-826 - add dependencies in classpath

CHANGELOG.md, USAGE_DATA.md, src/IntegrationUtils.ts, src/extension.ts, src/test/suite/StartIntegration.test.ts
command
- language of file by providing the extension; prefer to provide the extension to avoid to handle all potential cases of extension yaml/yml/YAML and surely other ways to write that I miss)
- main option of the command
it will give this kind of reports:
=> FUSETOOLS2-1036 - provide more precise telemetry for Start integration

src/test/suite/completion.util.ts
expected completion not found
the error will be something like:
```
7) Should do completion in yaml Camel K files without file name pattern
Completes for first level:
Error: Error: Timed out after waiting for 10000 ms
Cannot found expected completion "test" in the list of completions:
error-handler
from
my-added-property-for-the-demo
on-exception
rest
route
```
instead of somethign like:
```
1) Should do completion in Camel K standalone files
Completes additional dependencies:
Error: Timed out after waiting for 10000 ms
at /home/circleci/project/node_modules/async-wait-until/dist/index.js:1:1034
```
=> FUSETOOLS2-1094 - provide more precise error message in test failure for

src/test/suite/StartIntegration.test.ts
improved error message give something like:
```
1) Check can deploy default examples
Check basic deployments for each languages
Check can deploy Groovy example:
AssertionError: telemetry expected to be called once but was called 2. command;identifier: camelk.integrations.remove;language: undefined;kindundefined
command;identifier: camelk.startintegration;language: groovy;kindBasic - Apache Camel K Integration (no ConfigMap or Secret)
: expected false to be true
+ expected - actual
```
instead of:
```
1) Check can deploy default examples
Check basic deployments for each languages
Check can deploy Yaml example:
telemetry expected to be called once but was called 2
+ expected - actual
```
=> FUSETOOLS2-1093 - provide more information in case of test failure and await complete removal in teardown

CHANGELOG.md, README.md, package-lock.json, package.json, src/commands/StartJavaDebuggerCommand.ts, src/extension.ts, src/test/suite/DebugIntegration.test.ts, src/test/suite/StartIntegration.test.ts, src/test/suite/Utils/DeployTestUtil.ts, src/test/suite/kubectlwatcher.test.ts
~requires https://github.com/camel-tooling/vscode-camelk/pull/752/~
video for simple case: https://youtu.be/TQasRr1PiYw
scope and direct limitations:
- basic use case handled fo rlocalhost only (for remote https://issues.redhat.com/browse/FUSETOOLS2-1122 )
- multiple debug session launched in parallel handled
- contextual menu is always available and enable on right-click on Integrations (https://issues.redhat.com/browse/FUSETOOLS2-1126 )
- command is visible in command palette https://issues.redhat.com/browse/FUSETOOLS2-1127
=> Fusetools2 950 contexttual menu start java debugger

CHANGELOG.md, src/commands/StartJavaDebuggerCommand.ts
requires https://github.com/camel-tooling/vscode-camelk/pull/759
https://youtu.be/gQYYuVfeUjw
in fact, the `kamel debug` is a proxy to the remote instance. So from VS
Code, it is always connecting to the localhost and then `kamel debug` is
redirecting at the correct place
=> Fusetools2 1122 for remote instance

src/test/suite/DebugIntegration.test.ts, src/test/suite/Utils/DeployTestUtil.ts
a more precise conditional wait must be used due to automatic refresh
which is clearing the list of TreeNode and repopulating one by one
after.
=> FUSETOOLS2-1137 - ensure retrieving updated list of TreeNode

src/installer.ts, src/shell.ts, src/test/suite/versionUtils.test.ts, src/versionUtils.ts
Use an enum to detected the OS platform
Then decode it differently for kamel and kubectl.
Fixes #769
=> #769: Use an enum to detected the OS platform

src/config.ts, src/kamel.ts, src/kubectl.ts, src/kubectlutils.ts, src/task/CamelKDebugTaskDefinition.ts, src/task/CamelKRunTaskDefinition.ts
as reported as code smell by Sonar
https://sonarcloud.io/project/issues?id=vscode-camelk&resolved=false&rules=typescript%3AS4326&types=CODE_SMELL
=> Remove redundant use of `await` on a return value

src/IntegrationUtils.ts
instead.
see https://sonarcloud.io/project/issues?id=vscode-camelk&issues=AXe5MjvromOWeNW5TYmo&open=AXe5MjvromOWeNW5TYmo
=> 'isString' is deprecated. since v4.0.0 - use `typeof value === 'string'`

package.json
=> FUSETOOLS2-1127 - hide debugger cmd from palette

package.json, src/test/suite/CamelKSchemaManager.test.ts
modeline to Camel 3.10 version
The schema contains several modifications for several improvements and
new features. it will avoid users which relies on recent versions to
have troubles (such as in this issue
https://issues.apache.org/jira/browse/CAMEL-16741 )
For the future it would interesting to rely on the schemastore, see
https://issues.redhat.com/browse/FUSETOOLS2-1169
=> FUSETOOLS2-1168 - Upgrade default yaml schema for files with camel-k

src/test/suite/versionUtils.test.ts, src/versionUtils.ts
auto-upgrade is off and provided kamel version is not a community
released version
=> FUSETOOLS2-1168 - Avoid override on startup of the kamel binary when

.gitignore, .vscodeignore, CHANGELOG.md, package.json, src/extension.ts, src/ui-test/camelk_didact_tutorial_test.ts, src/ui-test/uitest_runner.ts
0.4.0
- Didact API has been modified so need to adapt
- provide basic test checking that the tutorial is registered and can be
opened. It requires to install VS Code Didact when launching UI tests.
- Register Didact tutorial at the beginning of the activation. It allows
to have it available without waiting for a potential download of kamel
CLI
- 1 workaround is used in testing due to not immediate loading of
Tutorial content in webview and
redhat-developer/vscode-extension-tester#301
- 1 workaround is used in testing due to not immediate loading of Didact
View tree and
redhat-developer/vscode-extension-tester#303
=> FUSETOOSL2-1174 - fix regression of registering tutorial with Didact

src/IntegrationUtils.ts, src/test/suite/StartIntegration.test.ts
based on https://github.com/camel-tooling/vscode-camelk/pull/821
done the FUSETOOLS2-679 and FUSETOOLS2-1191 in the mean time, as writing a test which is checking a wrong behavior doesn't make a lot of sense
=> Fusetools2 679 and FUSETOOLS2-1191 check start integration with property and remove the wrong double-quotes

src/test/runTests.ts
to workaround https://github.com/microsoft/vscode/issues/126636
Given that there is currently no workaround defined upstream, i think we should go with testing with previous version to unblock master
=> FUSETOOLS2-1200 - using previous VS Code version in test

src/extension.ts, src/test/suite/StartIntegration.test.ts, src/test/suite/StartIntegrationWithResource.test.ts, src/test/suite/Utils.ts, src/test/suite/Utils/DeployTestUtil.ts, src/test/suite/_completion/completion.java.test.ts, src/test/suite/integrationExplorer.test.ts, src/test/suite/kubectlwatcher.test.ts
based on https://github.com/camel-tooling/vscode-camelk/pull/842
Now that istnabul code coverage is removed, the spy in tests can be simplified. it also avoids to expose internal things in the extension API even if marked as "only for test"
=> Fusetools2 1202 simplify code

src/test/runTests.ts
a better workaround which allows to launch test on latest VS Code version
suggested here https://vscode-dev-community.slack.com/archives/C74CB59NE/p1625851199328400?thread_ts=1625823881.321300&cid=C74CB59NE
=> FUSETOOLS2-1200 - disable workspace trust when launching tests

package-lock.json, package.json
based on https://github.com/camel-tooling/vscode-camelk/pull/844 (to simplify the update)
=> FUSETOOLS2-1154 - Upgrade red hat telemetry to 0.2.0

CHANGELOG.md, README.md, src/codelenses/ClasspathRefreshCodeLensProvider.ts, src/extension.ts, src/test/suite/codelenses/ClasspathRefreshCodeLensProvider.test.ts
Currently, the command to refresh classpath dependency is provided as a
command which requires the user to know that it exists. By providing it
as codelens in this PR on top of a Camel  K modeline inside Java files, it will
spread knowledge of this capability. Also it will require less click.
=> FUSETOOLS2-1208 - Provide CodeLens to refresh classpath dependencies

CHANGELOG.md, README.md, src/codelenses/StartIntegrationCodeLensProvider.ts, src/extension.ts, src/test/suite/Utils/DeployTestUtil.ts, src/test/suite/codelenses/ClasspathRefreshCodeLensProvider.test.ts, src/test/suite/codelenses/StartIntegrationCodeLens.test.ts, test Fixture with speci@l chars/test-codelens-with-modeline.yaml, test Fixture with speci@l chars/test-codelens.camelk.yaml
- available for all types of files with heuristic:
- have *.camelk.* in file name
- or have Camel K modeline
- currently triggers the command to "Start Integration", it lets up to the user to choose which kind of start he wants. In the future, we might decide to pick basic, or dev or debug or an associated task or the latest one used? But it is the easiest to implement as a first iteration and it already provides a lot of improvement
-  there is no test executing the codelenses. I have not found a way to do it programmatically through VS Code API. I reported this issue to provide a UI test https://issues.redhat.com/browse/FUSETOOLS2-1213
- Readme and tutorials remains valid to start an integration. That said, it might be nice to update them to include the usage of the Codelens. Reported …
=> FUSETOOLS2-1128 - Provide Start CodeLens on Camel K files

CHANGELOG.md, package-lock.json, package.json, src/logUtils.ts
- the log view doesn't support ansi code (would be better to support it
but requires more work and also would be better to synchronize with VS
Code Kubernetes as the Ui was picked from there to stay consistent)
- currently using 6.0.0 instead of 7.0.0 as otherwise there is this
error preventing VS Code extension to activate:
```
Activating extension 'redhat.vscode-camelk' failed: Must use import to
load ES Module:
/home/xx/git/vscode-camelk/node_modules/strip-ansi/index.js
require() of ES modules is not supported.
require() of /home/xx/git/vscode-camelk/node_modules/strip-ansi/index.js
from /home/xx/git/vscode-camelk/out/src/logUtils.js is an ES module file
as it is a .js file whose nearest parent package.json contains "type":
"module" which defines all .js files in that package scope as …
```
=> FUSETOOLS2-1236 - strip ansi code sent to log

Jenkinsfile
the default branch for Jenkins git plugin is master
=> FUSETOOLS2-1295 - fix jenkins file to use main branch

.circleci/config.yml, package.json, src/test/suite/_completion/completion.java.test.ts
3 different things were broken in the last week so requires to mix the 3 things in same PR to have a green build:
- FUSETOOLS2-1359 - avoid use of sudo to install global npm dependencies on Circle CI. It was previously required, now it is causing build failures. See https://stackoverflow.com/questions/50915469/simple-circleci-2-0-configuration-fails-for-global-npm-package-installation for workaround
- FUSETOOLS2-1359 - fix vsce version to a compatible with node 12.x. otherwise, it is picking the latest version available which now requires node 14 
- FUSETOOLS2-1358 - use more specific activation event. It allows to build with vsce without specific flag since they introduced yet again a blocking warning which supposedly improve performance (which is pretty negligeable in our case as long …
=> 1359 fix main branch

package-lock.json, package.json
possible since upgrade of vscode-uitests-tooling to 2.2.1
it will allow compatibility with node 16 and simplify maintenance
=> FUSETOOLS2-1393 - remove deprecated vscode-extension-tester-native

src/test/suite/integrationExplorer.test.ts
the expected value was set in the message parameter of the function
detected by Sonar:
https://sonarcloud.io/project/issues?id=vscode-camelk&issues=AX5ESgERcEULlLhCWUbc&open=AX5ESgERcEULlLhCWUbc
https://sonarcloud.io/project/issues?id=vscode-camelk&issues=AX5ESgERcEULlLhCWUbd&open=AX5ESgERcEULlLhCWUbd
=> Fix assertions in test

.circleci/config.yml, CHANGELOG.md, package.json, src/JavaDependenciesManager.ts, src/test/suite/CamelKTaskCompletionItemProvider.test.ts, src/test/suite/StartIntegration.test.ts, src/test/suite/StartIntegrationWithResource.test.ts, src/test/suite/versionUtils.test.ts, src/versionUtils.ts
implies upgrade of dependencies Camel to 3.14.0
=> FUSETOOLS2-1450 - upgrade default Camel K to 1.8.0

.circleci/config.yml, CHANGELOG.md, package.json, src/JavaDependenciesManager.ts, src/test/suite/StartIntegrationWithResource.test.ts, src/test/suite/versionUtils.test.ts, src/versionUtils.ts
note that previous regression to deploy several resources has unfortunately not been fixed in Camel K 1.8.1 despite it was marked as such. Opened a new issue https://github.com/apache/camel-k/issues/3077
=> FUSETOOLS2-1456 - upgrade default Camel K to 1.8.1

.circleci/config.yml
=> Use 1.9.2 to install the Camel K cluster in tests

package.json
=> FUSETOOLS2-1645: Camel K extension cannot be compiled on WIN because ESLint

src/installer.ts, src/shell.ts
Enum value for the windows platform was `0`
As a result of this value [condition](https://github.com/camel-tooling/vscode-camelk/blob/main/src/installer.ts#L137) received 0(false) in it.
And consequently, the stage of assembling the URL for the subsequent installation of the `kamel` was skipped with the error:
`Camel K CLI Version 1.9.2 unavailable. Please check the Apache Camel K version specified in VS Code Settings. Inaccessible url:`
More information:
[1] Initial issue - https://github.com/camel-tooling/vscode-camelk/issues/769
[2] RH issue - https://issues.redhat.com/browse/FUSETOOLS2-1140
[3] PR with enum addition - https://github.com/camel-tooling/vscode-camelk/pull/770
=> [FUSETOOLS2-1140] Fix enum for windows platform

package-lock.json, package.json, src/logUtils.ts
After users select `Follow log for running Apache Camel K Integration` log output will be frozen with `Waiting for integration simple to start...` message due to [code line ](https://github.com/camel-tooling/vscode-camelk/blob/main/src/logUtils.ts#L56)
The issue can be solved with the `strip-ansi` version downgrade from 7.0.1 to 6.0.1
Related commits:
[1] [Bump strip-ansi from 6.0.0 to 7.0.1](https://github.com/camel-tooling/vscode-camelk/commit/7284c0ac3004c2f7a411e20cf68e9aa6b6c881e4)
[2] [fixed issue with import of strip-ansi](https://github.com/camel-tooling/vscode-camelk/commit/0d78be9435ccd7925f163c5d9d63c9542ce5aa71)
[3] [FUSETOOLS2-1236 - strip ansi code sent to log](https://github.com/camel-tooling/vscode-camelk/commit/b886fcce26eb1be4f77a24bc55d8473cb301bccd)
Related issues:
[1] …
=> [FUSETOOLS2-1652] Regress strip-ansi from 7.0.1 to 6.0.1

.circleci/config.yml
=> FUSETOOLS2-1566 - upgrade node on Circle CI to version 16

package-lock.json
used npm 16.15.1 and called npm install
```
(base) [apupier@localhost vscode-camelk]$ npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
added 9 packages, changed 6 packages, and audited 743 packages in 22s
111 packages are looking for funding
run `npm fund` for details
2 moderate severity vulnerabilities
To address all issues (including breaking changes), run:
npm audit fix --force
Run `npm audit` for details.
(base) [apupier@localhost vscode-camelk]$ npm version
{
'vscode-camelk': '0.0.32',
npm: '8.11.0',
node: …
```
=> FUSETOOLS2-1723 - upgrade package-lock.json to version 2

package-lock.json, package.json
given that "This is a stub types definition. nock provides its own type
definitions, so you do not need this installed."
=> FUSETOOLS2-1709 - remove @types/nock

CHANGELOG.md, README.md, package.json, src/test/suite/_completion/completion.java.test.ts, src/ui-test/tests/create_integration_file_test.ts, src/ui-test/utils/utils.ts
Link to issue: https://issues.redhat.com/browse/FUSETOOLS2-1120
After Aurelien investigation and a chat, we decided to put these two extensions as extensionDependencies.
I have removed/changed the mention to them in Readme and also removed the setup for those extensions on the integration tests. After searching through the code I couldn't find any more mentions/uses.
=> [FUSETOOLS2-1120] Adds VSCode Java Debugger and VSCode Language support for Java as extensionDependencies

src/test/suite/_completion/completion.java.test.ts, src/test/suite/completion.util.ts
Hi,
I have found that after the first `camelk.classpath.refresh` command config file is updated with the right dependencies, however, the `checkExpectedCompletion` function ignores it.
If dependencies are refreshed two times updated config file (SAME) will be recognized and `checkExpectedCompletion` pass without errors.
@apupier Do you have any ideas where I can search for the root of that problem?
But anyway, we can open an extra issue and unblock tests with that double refresh :thinking:
=> FUSETOOLS2-2061 Call refresh two times

package-lock.json, package.json
there was this warning since upgrade to mkdirp 3.0.1: `npm WARN deprecated @types/mkdirp@2.0.0: This is a stub types definition. mkdirp provides its own type definitions, so you do not need this installed.`
=> Remove no more needed @types/mkdirp

.github/workflows/insider.yml, .github/workflows/main.yml, Jenkinsfile
On Jenkins CI host, the ipV6 is now deactivated.
otherwise somewhere between the host and the npmjs website ipV6, a layer is not handling it correctly.
=> FUSETOOLS2-2176 - use Node 18 for build

.github/workflows/insider.yml, .github/workflows/main.yml, CHANGELOG.md, README.md, docs/content/java-support.md, package.json, src/JavaDependenciesManager.ts, test Fixture with speci@l chars/MyRouteBuilderWithAdditionalDependencies.java
- `kamel local` has been removed from kamel cli 2.x
- Adding requirement on JBang CLI to do the same action
let's start with a lot less ambitious change because after investigation it sounds moving things to a better way using JDT-LS capabilities (similar to what VS Code JBang is doing) and in VS Code language Support will be even larger than I initially thought.
=> FUSETOOLS2-1888 - remove dependency on `kamel local`

.github/workflows/insider.yml, .github/workflows/main.yml
GitHub released a new image by default for which the way to install kubectl has been modified
https://github.com/actions/runner-images/commit/567d74923a1b56a0cac40c5f59a22b451c97eda5. Removing access from command-line is then different.
=> Fix main branch build on CI after image change

CHANGELOG.md, src/JavaDependenciesManager.ts
For not clearly defined reasons (that we are able to find), on some MacOS machines, the current working directory used by default by Node.js execSync method is not picked by correctly by Camel Jbang. Using the workspace folder is workarounding the issue.
In regular cases, there will be a workspace folder available.
fix #1698
=> Fix refresh of classpath for some MacOS

.github/workflows/OtherOSes.yml, .github/workflows/main.yml, README.md, src/test/suite/CamelKSchemaManager.test.ts
* we need to space out request to GitHub to retrieve the file content against we want to check
* Test with 1.85.2 instead of latest 1.86. It is failing with 1.86.x. Cannot reproduce manually even if behavior seems inconsistent, it is always possible to refresh classpath several times and/or close/reopen and it finishes to work. To unblock main branch, test with 1.85 and add a note in readme. Reported https://issues.redhat.com/browse/FUSETOOLS2-2311 to tackle it in another phase.
=> Fix main branch

CHANGELOG.md, src/JavaDependenciesManager.ts
@djelinek Can you try this PR on MacOS please?
=> Fusetools2 2352 Use Extension storage folder as working directory for Camel JBang working directory on MacOS

src/test/runTests.ts
latest Node security release
see https://github.com/nodejs/node/issues/52554#issuecomment-2060026269
=> FUSETOOLS2-2371: provide workaround to install VS Code extensions with

src/test/runTests.ts
previously it was always marking it as success even if it wasn't the case
=> Improving message of installation of extension for tests

.github/workflows/OtherOSes.yml, .github/workflows/main.yml, src/test/suite/completion.util.ts
on Windows and Mac, the returned completion has a different structure in some cases starting with VS Code 1.86+.
=> FUSETOOLS2-2311 - fix tests with VS Code 1.86+
