camel-tooling/vscode-camelk

CHANGELOG.md
README.md
configure-minikube-camelk.md
package.json
src/extension.ts

updating readme and adding initial stab at Java integration support

---

package.json
src/extension.ts

updating command ids to avoid clashes and fixing code issue

---

resources/round-k-transparent-16.svg
resources/round-k-transparent.svg
src/CamelKNodeProvider.ts

adding new k in a circle icon for integrations

---

sonar-project.properties

adding sonar file

---

README.md
package-lock.json
package.json

update version to 0.0.2 and fix readme image problem

---

CHANGELOG.md
package-lock.json
package.json

updating to version 0.0.3 and updating changelog

---

CHANGELOG.md

updating changelog ahead of 0.0.3 release

---

CHANGELOG.md
package-lock.json
package.json

update version to 0.0.4 for additional work

---

CHANGELOG.md
package-lock.json
package.json

it is saving space in the final vsix binary

Move test dependencies to devDependencies #35

---

CHANGELOG.md
package-lock.json
package.json

Prepare next iteration 0.0.5

---

Contributing.md
Jenkinsfile

fixing submitter list so we can publish vscode-camelk via jenkins

---

package.json
src/CamelKJSONUtils.ts
src/extension.ts
src/test/camelkjsonutils.test.ts
src/test/gocamelkkubernetes.test.ts

issue #25 - removing --dev setting for camel-k executable deployment and improving proxy url support

---

src/CamelKNodeProvider.ts

issue #60 - get integration status from json returned by rest call

---

CHANGELOG.md
package-lock.json
package.json

updating version to 0.0.7 for additional work

---

CHANGELOG.md
package.json

Update to name approved by Red Hat legal department #72

---

CHANGELOG.md
src/CamelKJSONUtils.ts
src/extension.ts

issue #67 - avoid refreshing integrations view if collapsed

---

configure-minikube-camelk.md
vsc-extension-quickstart.md

issue #71 and issue #31 - updating development docs

---

CHANGELOG.md
package-lock.json
package.json

Prepare for next iteration 0.0.8

---

.travis.yml

Exclude dependabot branches from non-PR jobs #100

---

CHANGELOG.md
package-lock.json
package.json

prepare next iteration release 0.0.9

---

src/ConfigMapAndSecrets.ts
src/IntegrationUtils.ts

issue #106 - restructuring integration menu dropdown code

---

.travis.yml
CHANGELOG.md
package-lock.json
package.json
src/extension.ts
src/test/camelkjsonutils.test.ts
src/test/extension.test.ts
src/test/integrationExplorer.test.ts

issue #65 - adding extension dependency for k8s extension

---

CHANGELOG.md
src/CamelKJSONUtils.ts
src/IntegrationUtils.ts

issue #56 - adding dev mode option

---

CHANGELOG.md
src/CamelKNodeProvider.ts
src/IntegrationUtils.ts

issue #52 - adding --resource integration capability

---

.vscode/extensions.json

Update recommended TS Lint extension

---

CHANGELOG.md
package-lock.json
src/IntegrationUtils.ts
src/extension.ts

issue #54 - adding support for deploying with a property

---

src/extension.ts

Starting to make code more readable.

extracting logic from activate into separate functions

---

src/CamelKJSONUtils.ts
src/CamelKNodeProvider.ts
src/ConfigMapAndSecrets.ts
src/IntegrationUtils.ts
src/extension.ts

another Promise refactoring 

---

src/IntegrationUtils.ts
src/extension.ts

migrating child process exec to spawn to avoid hanging process

---

package-lock.json
package.json

updating version to 0.0.10 for new development

---

README.md

Update outdated links inside README.md file

---

package.json
src/CamelKNodeProvider.ts
src/config.ts
src/extension.ts
src/kamel.ts
src/kubectl.ts
src/kubectlutils.ts

FUSETOOLS2-10 Adding Namespace Support

---

package-lock.json
package.json
src/extension.ts

bump vscode and tar versions

---

README.md

Fixing minor issue in readme for Issue #167

---

src/CamelKNodeProvider.ts

issue #171 - fixing issue with CamelKNodeProvider not throwing catch

---

src/extension.ts

issue #143 - fixing issue when starting log

---

src/installer.ts

fixed broken download of Kamel executable

---

package-lock.json

fixing package vulnerability

---

src/test/suite/index.ts

it allows to generate test results that jenkins build is using.

Add back the Mocha jenkins Reporter #185

---

package.json
src/CamelKNodeProvider.ts
src/config.ts
src/kamel.ts
src/kubectl.ts
src/kubectlutils.ts
src/test/suite/extension.test.ts
src/test/suite/kamel.test.ts

FUSETOOLS2-10 - making namespace support optional

---

README.md

updating readme section slightly with optional namespace setting change

---

CHANGELOG.md

update changelog for 0.0.10 release

---

CHANGELOG.md
package-lock.json
package.json

updating to version 0.0.11 for future work

---

.gitignore
.travis.yml
.vscode/launch.json
.vscodeignore
package-lock.json
package.json
src/test/runTests.ts
src/test/suite/camelkjsonutils.test.ts
src/ui-test/camelk_extension_test.ts
tsconfig.json
tslint.json

Prepare UI tests for Camel-K for VS Code - extension installation info

---

package-lock.json
package.json
src/installer.ts

issue #180 - changing download approach and adding progress indicator

---

src/installer.ts

updating camel k runtime default version to 1.0.0-M3

---

package-lock.json
package.json

bumping @types/vscode from 1.39 to 1.40

---

package-lock.json
package.json
src/ui-test/camelk_extension_test.ts

Update 'vscode-extension-tester' to verssion 2.1.0 which fix failing UI tests

---

src/installer.ts

fixing issue discovered testing install on mac

---

src/installer.ts

updating to Camel K version 1.0.0-M4

---

src/CamelKNodeProvider.ts
src/extension.ts
src/test/suite/integrationExplorer.test.ts

FUSETOOLS2-60 fixing treeview images so they appear again

---

package-lock.json
package.json
src/ui-test/camelk_extension_test.ts

Update tests to changes in vscode-uitests-tooling 2.0.0

---

src/downloader.ts
src/kubectlutils.ts
src/test/suite/install.test.ts
src/test/suite/integrationExplorer.test.ts

FUSETOOLS2-52 - retrieving client instead of runtime version of kubectl

---

CHANGELOG.md
src/JavaDependenciesManager.ts
src/installer.ts

FUSETOOLS2-186 - upgrade default Kamel client to 1.0.0-RC1

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.12

---

.travis.yml
Jenkinsfile

FUSETOOLS2-209 - remove useless --ignore-scripts call in CI build config

---

package-lock.json
package.json

Fix UI Tests missing opencv module error

---

src/extension.ts

Remove no longer needed comment #287

---

CHANGELOG.md
package-lock.json
package.json

updating version to 0.0.13

---

package-lock.json
package.json

Bumping @types/vscode from 1.41.0 to 1.42.0 and updating engine version

---

CHANGELOG.md
src/JavaDependenciesManager.ts
src/installer.ts

FUSETOOLS2-239 - update to runtime 1.0.0-RC2

---

CHANGELOG.md
package-lock.json
package.json
src/config.ts
src/extension.ts
src/installer.ts
src/test/suite/extension.test.ts
src/test/suite/install.test.ts
src/versionUtils.ts

issue #280 - first cut of setting to avoid auto-upgrade of kamel cli

---

CHANGELOG.md
package-lock.json
package.json

updating version to 0.0.14 for next round of work

---

.travis.yml
src/extension.ts
src/kubectl.ts
src/test/suite/Utils.ts
src/test/suite/completion.java.test.ts
src/test/suite/install.test.ts
src/test/suite/integrationExplorer.test.ts
src/test/suite/kubectlwatcher.test.ts

FUSETOOLS2-304 - provide minikube on Travis CI

---

src/IntegrationUtils.ts
src/test/suite/IntegrationUtils.test.ts

requires https://github.com/camel-tooling/vscode-camelk/pull/400

Fusetools2 310 fix unable to call kamel when called from right click

---

.travis.yml

FUSETOOLS2-349 - upgrade kubectl from 1.17.4 to 1.18.2

---

src/commands/NewIntegrationFileCommand.ts
src/test/suite/commands/NewIntegrationFileCommand.test.ts

FUSETOOLS2-429 - support path with space for creation of new Camel K

---

CHANGELOG.md

FUSETOOLS2-475 - add Didact tutorial mention in Changelog

---

CHANGELOG.md
package-lock.json
package.json

Prepare next iteration development 0.0.15

---

CHANGELOG.md
src/task/TraitManager.ts
src/test/suite/_completion/completion.tasks.test.ts
src/test/suite/completion.util.ts

FUSETOOLS2-419 - add default value for trait property completion

---

src/IntegrationUtils.ts
src/commands/NewIntegrationFileCommand.ts
src/extension.ts
src/logUtils.ts
src/task/TraitManager.ts

FUSETOOLS2-348 - change naming for clarity kamelExe -> kamelExecutor

---

CHANGELOG.md
src/task/TraitDefinition.ts
src/task/TraitManager.ts
src/task/TraitProperty.ts
src/test/suite/_completion/completion.tasks.test.ts
src/test/suite/completion.util.ts
src/test/suite/index.ts

FUSETOOLS2-291 - provide description for trait completion in tasks.json

---

.travis.yml
CHANGELOG.md
configure-minikube-camelk.md
src/versionUtils.ts

FUSETOOLS2-544 - upgrade to Camel K 1.0.1

---

CHANGELOG.md
package-lock.json
package.json

Prepare next iteration 0.0.16

---

Jenkinsfile

test on Jenkins with this job: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/VS%20Code/job/vscode-camelk-release/648/

FUSETOOLS2-443 - publish release to open-vsx.org too

---

src/test/suite/index.ts

reverting to previous state to enable all tests

---

src/versionUtils.ts

refactoring versionUtils.ts

---

src/CamelKNodeProvider.ts
src/extension.ts
src/kamel.ts
src/kubectl.ts
src/shell.ts
src/test/suite/install.test.ts

refactored kamel.ts and fixed some errors caused by incorrect catches

---

src/kubectlutils.ts

refactoring of kubectlutils.ts

---

src/IntegrationUtils.ts
src/installer.ts

refactored installer.ts

---

src/ConfigMapAndSecrets.ts
src/downloader.ts

refactored ConfigMapAndSecrets.ts and downloader.ts

---

.travis.yml
CHANGELOG.md
package.json
src/extension.ts
src/installer.ts
src/test/suite/_completion/completion.tasks.test.ts
src/test/suite/versionUtils.test.ts
src/versionUtils.ts

starting to work on the problem

---

src/CamelKNodeProvider.ts

refactoring of CamelKNodeProvider.ts

---

src/extension.ts
src/test/suite/Utils.ts
src/test/suite/kubectlwatcher.test.ts

refactor of extension.ts

---

src/test/suite/_completion/completion.java.test.ts

attempting to do more optional chaining

---

src/test/suite/_completion/completion.java.test.ts

increasing timeout to see if that helps

---

src/test/suite/_completion/completion.java.test.ts

skipping test until we can fix it on Jenkins

---

CHANGELOG.md
package-lock.json
package.json

updating version to 0.0.17

---

Contributing.md

FUSETOOLS2-607 - add information to update Che registry after VS Code

---

CHANGELOG.md
package.json
src/CamelKSchemaManager.ts
src/test/suite/CamelKSchemaManager.test.ts

FUSETOOLS2-571 - provide setting to change the default Camel K schema

---

src/commands/NewIntegrationFileCommand.ts

refactored NewIntegrationFileCommand.ts

---

src/test/suite/_completion/completion.java.test.ts

adding check for jenkins for completion test

---

src/test/suite/install.test.ts

I created https://issues.redhat.com/browse/FUSETOOLS2-713 to try to avoid breaking the master on each Camel K release.
we can notice that the test is failing with a more precise message here https://travis-ci.org/github/camel-tooling/vscode-camelk/builds/729248437#L711 This is checked via separate temporary branch/[PR](https://github.com/camel-tooling/vscode-camelk/pull/555) because the test requires to have access to github token.

FUSETOOLS2-709 - refactor test to have more information on failure

---

src/IntegrationUtils.ts
src/kamel.ts

noticeably including namespace parameter if used

FUSETOOLS2-572 - provide more accurate command called in console log

---

.travis.yml

FUSETOOLS2-712 - upgrade minikube to 1.13.1 on Travis infra

---

.travis.yml

FUSETOOLS2-711 - upgrade kubectl to 1.19.0 in Travis infra

---

CHANGELOG.md
package-lock.json
package.json

Prepare for next development iteration 0.0.18

---

src/commands/NewIntegrationFileCommand.ts
src/test/suite/StartIntegration.test.ts

tests results can be seen here: https://travis-ci.org/github/camel-tooling/vscode-camelk/builds/731349784#L662-L700

FUSETOOLS2-674 - add automated test of basic deployment for all DSLs

---

Jenkinsfile

to be synchronized with https://gitlab.mw.lab.eng.bos.redhat.com/dev-platform/cci-config/merge_requests/188

FUSETOOLS2-761 - use GitHub token configured in CI environment

---

src/task/CamelKTaskDefinition.ts
src/test/suite/StartIntegration.test.ts

requires https://github.com/camel-tooling/vscode-camelk/pull/569 and https://github.com/camel-tooling/vscode-camelk/pull/570

FUSETOOLS2-681 - provide test for default task

---

CHANGELOG.md

Add Camel K default version upgrade to 1.2.0 in changelog

---

CHANGELOG.md
package-lock.json
package.json

Prepare for next development iteration 0.0.19

---

Jenkinsfile

to have poll trigger workign with PipelineJob

FUSETOOLS2-784 use .git suffix

---

README.md

FUSETOOLS2-825 - update badge for Travis moving from .org to .com

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.21

---

sonar-project.properties

FUSETOOLS2-993 - fix sonar configuration for ui tests

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.22

---

README.md
USAGE_DATA.md
package-lock.json
package.json
src/commands/NewIntegrationFileCommand.ts
src/extension.ts
src/test/runTests.ts

https://snapshot.woopra.com/5GeHozdVXv4ujHQiSigFTx4oQrhfF6NsCMMikBkSmgQ3xNLcyuouWzs2BScnU6EGi8

FUSETOOLS2-1033 telemetry integration creation

---

CHANGELOG.md

FUSETOOLS2-1033 - changelog - provide telemetry for Camel K Integration

---

src/Telemetry.ts
src/commands/NewIntegrationFileCommand.ts
src/extension.ts
src/test/suite/commands/NewIntegrationFileCommand.test.ts
src/test/suite/index.ts

creation
extracting the code in a specific file allows to spy the correct instance/method.

FUSETOOLS2-1033 - Provide test for telemetry of Integration file

---

CHANGELOG.md
package-lock.json
package.json

prepare next development iteration 0.0.23

---

package-lock.json
package.json

Signed-off-by: Dominik Jelinek <djelinek@eredhat.com>

vscode-extension-tester 4.0.2 and vscode-uitests-tooling 2.0.2

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.24

---

.circleci/config.yml
src/test/runTests.ts

FUSETOOLS2-443 - Provide nightly build for basic test on VS Code

---

.circleci/config.yml

Update minikube used for test to 1.18.1

---

.circleci/config.yml
package.json

based on https://github.com/camel-tooling/vscode-camelk/pull/727

FUSETOOLS2-443 - test against insider for UI tests

---

.circleci/config.yml

update to latest minikube

---

.circleci/config.yml
CHANGELOG.md
src/JavaDependenciesManager.ts
src/test/suite/versionUtils.test.ts
src/versionUtils.ts

FUSETOOLS2-1066 - switching to latest Camel K version 1.4.0

---

src/extension.ts
src/test/suite/StartIntegration.test.ts
src/test/suite/index.ts

based on https://github.com/camel-tooling/vscode-camelk/pull/744

Fusetools2 1093 fix flakiness second iteration

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.25

---

CHANGELOG.md
package-lock.json
package.json

prepare next development iteration 0.0.26

---

src/CamelKNodeProvider.ts
src/kubectlutils.ts

as recommended by Sonar
https://sonarcloud.io/project/issues?id=vscode-camelk&open=AXe5MjsIomOWeNW5TYmX&resolved=false&rules=typescript%3AS4138&types=CODE_SMELL

Use `for-of` loop instead of a `for` loop

---

src/kamel.ts
src/kubectl.ts

reported by Sonar
https://sonarcloud.io/project/issues?id=vscode-camelk&resolved=false&rules=typescript%3AS3863

Remove duplicated import

---

CHANGELOG.md
src/test/suite/CamelKTaskCompletionItemProvider.test.ts
src/test/suite/versionUtils.test.ts
src/versionUtils.ts

Upgrade default Camel K to 1.4.1

---

src/IntegrationUtils.ts
src/test/suite/StartIntegration.test.ts

very basic test, only checking that the integration is running, not
checking that the configmap can be effectively used. Created https://issues.redhat.com/browse/FUSETOOLS2-1196 to test further

FUSETOOLS2-676 - provide test for deploy with ConfigMap

---

src/test/suite/StartIntegration.test.ts

based on https://github.com/camel-tooling/vscode-camelk/pull/811

Fusetools2 1196 provide assertion on what is available

---

src/IntegrationUtils.ts
src/test/suite/StartIntegration.test.ts

based on https://github.com/camel-tooling/vscode-camelk/pull/811

Fusetools2 677 providetest for deploy with secret

---

.circleci/config.yml

Upgrade minikube from 1.19 to 1.21

---

.circleci/config.yml

Upgrade Kubernetes used for test from 1.20 to 1.21

---

src/IntegrationUtils.ts
src/test/suite/CamelKRunTaskDefinition.test.ts
src/test/suite/StartIntegrationWithResource.test.ts

FUSETOOLS2-678 FUSETOOLS2-1172 Fix start integration with resource and provide test

---

CHANGELOG.md
package.json
src/IntegrationUtils.ts
src/task/CamelKRunTaskDefinition.ts
src/test/suite/CamelKRunTaskDefinition.test.ts
src/test/suite/StartIntegrationWithResource.test.ts

based on https://github.com/camel-tooling/vscode-camelk/pull/823

Fusetools2 1197 support multiple resources

---

package.json
src/Telemetry.ts
src/extension.ts
src/test/runTests.ts

requires https://github.com/camel-tooling/vscode-camelk/pull/842

Fusetools2 1154 telemetry update without istanbul

---

.circleci/config.yml
CHANGELOG.md
src/JavaDependenciesManager.ts
src/test/suite/CamelKTaskCompletionItemProvider.test.ts
src/test/suite/StartIntegration.test.ts
src/test/suite/versionUtils.test.ts
src/versionUtils.ts

it includes upgrade to Camel 3.11.0

Upgrade default kamel version to 1.5.0

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.28

---

.circleci/config.yml
didact/camelk/first-integration.md

to update naming in GitHub Web Ui before merging.
To synchronize with https://gitlab.cee.redhat.com/codeready-studio/cci-config/-/merge_requests/453

FUSETOOLS2-1295 - Migrate default branch from master to main

---

src/task/CamelKDebugTaskDefinition.ts
src/task/CamelKRunTaskDefinition.ts
src/test/suite/CamelKDebugTaskDefinition.test.ts
src/test/suite/StartIntegration.test.ts
src/test/suite/StartIntegrationWithResource.test.ts

FUSETOOLS2-1108 - support space in path of VS Code installation for

---

src/test/suite/StartIntegration.test.ts

installation
to fix https://app.circleci.com/pipelines/github/camel-tooling/vscode-camelk/1391/workflows/ab07f8bc-8957-4ae2-aa30-cabe7bcacd42/jobs/1709?invite=true#step-111-919

FUSETOOLS2-1108 - fix tests when there is space in path to VS Code

---

CHANGELOG.md
package.json

part of Azure/vscode-kubernetes-tools#985

Add keyword for discovery of extension when using Camel Yaml DSL

---

CHANGELOG.md
package.json

Upgrade to 3.13.0 Yaml schema by default

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.29

---

.circleci/config.yml
Jenkinsfile

FUSETOOLS2-1411 - specify node 14 where possible in CI

---

src/ui-test/camelk_extension_test.ts

https://sonarcloud.io/project/issues?id=vscode-camelk&issues=AX5ESgHhcEULlLhCWUbe&open=AX5ESgHhcEULlLhCWUbe

Provide a minimal assertion in the test

---

src/test/suite/StartIntegration.test.ts
src/test/suite/StartIntegrationWithResource.test.ts
src/test/suite/Utils/DeployTestUtil.ts

Write to console output to avoid CI to timeout because there is no

---

package.json

FUSETOOLS2-1490 - add Red Hat telemetry setting

---

.circleci/config.yml

Upgrade minikube used in CI to 1.25.2

---

.circleci/config.yml

Upgrade Kubernetes used in CI to 1.23.4

---

README.md

it is even one of the main one currently

remove experimental note for yaml dsl

---

.circleci/config.yml
CHANGELOG.md
src/test/suite/versionUtils.test.ts
src/versionUtils.ts

FUSETOOLS2-1530 upgrade Camel K to 1.8.2 by default

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.31

---

.circleci/config.yml
CHANGELOG.md
package.json
src/JavaDependenciesManager.ts
src/kamel.ts
src/test/suite/CamelKTaskCompletionItemProvider.test.ts
src/test/suite/versionUtils.test.ts
src/versionUtils.ts

FUSETOOLS2-1531 - Use Camel K 1.9.0

---

CHANGELOG.md
src/test/suite/versionUtils.test.ts
src/versionUtils.ts

FUSETOOLS2-1634 - upgrade default to 1.9.2

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.32

---

src/ui-test/camelk_extension_test.ts
src/ui-test/uitest_runner.ts
src/ui-test/utils/waitConditions.ts

FUSETOOLS-1618: [vscode-camelk] Stabilize UI tests pipelines on all operating systems

---

src/IntegrationConstants.ts
src/IntegrationUtils.ts
src/commands/NewIntegrationFileCommand.ts
src/test/suite/DebugIntegration.test.ts
src/test/suite/IntegrationUtils.test.ts
src/test/suite/StartIntegration.test.ts
src/test/suite/StartIntegrationWithResource.test.ts
src/test/suite/Utils/DeployTestUtil.ts
src/ui-test/camelk_extension_test.ts
src/ui-test/dev_integration_test.ts
src/ui-test/uitest_runner.ts
src/ui-test/utils/resourcesUtils.ts
src/ui-test/utils/uiTestConstants.ts
src/ui-test/utils/waitConditions.ts

Hi, I have added the UI test for developer mode for all os (RHEL, Fedora, Ubuntu, Windows, MacOS).
Also, it was tested with OCP (4.9/4.10) with productized camel-k (1.6.6/1.6.7)
Note: not UI test updates were made to avoid import errors with vscode library
- [src/IntegrationConstants.ts](https://github.com/camel-tooling/vscode-camelk/compare/main...unsortedhashsets:vscode-camelk:first-integration-test#diff-df9971261162ce8050c6aa16e6f5e769c4af9525e07ae2377e6781fa77ed186d) (New)
- [src/IntegrationUtils.ts](https://github.com/camel-tooling/vscode-camelk/compare/main...unsortedhashsets:vscode-camelk:first-integration-test#diff-6541ecefb2f9f7e6e01fdb6799a9eae31eb16d62e3eee34ed4c74843876c0e24)
- [src/commands/NewIntegrationFileCommand.ts](https://github.com/camel-tooling/vscode-camelk/compare/ma …

[FUSETOOLS2-163] Add Dev Mode UI tests

---

package-lock.json
package.json

requires https://github.com/camel-tooling/vscode-camelk/pull/1207

1711 remove request-promise

---

package-lock.json
package.json
src/test/runTests.ts

WIP: Wanting to test the migration on github ci.
Related issue: https://issues.redhat.com/browse/FUSETOOLS2-1731

FUSETOOLS2-1731: Migrating to @vscode/test-electron package

---

README.md

to be merged after https://github.com/camel-tooling/vscode-camelk/pull/1287

FUSETOOLS2-1830 - fix dead links in readme

---

.circleci/config.yml
CHANGELOG.md
package-lock.json
package.json
src/JavaDependenciesManager.ts
src/test/suite/CamelKTaskCompletionItemProvider.test.ts
src/test/suite/kubectlwatcher.test.ts
src/test/suite/versionUtils.test.ts
src/ui-test/utils/waitConditions.ts
src/versionUtils.ts

2 problems collided that both broke the main branch, so need to fix both of them at same time to have working main branch:
- Camel K 1.11 release which requires small adaptation in tests
- VS Code 1.74 release which requires upgrade of vscode-extension-tester

FUSETOOLS2-1887 - upgrade default version to Camel K 1.11.0

---

CHANGELOG.md
docs/content/integration.md
package.json
src/CamelKSchemaManager.ts
src/IntegrationConstants.ts
src/IntegrationUtils.ts
src/test/suite/StartIntegration.test.ts
test Fixture with speci@l chars/TestBasicYmlDeploy.camel.yml

only minimal test added which is notably not checking the visibility of commands.

FUSETOOLS2-2189 - Support *.yml files

---

src/CamelKNodeProvider.ts
src/IntegrationUtils.ts
src/extension.ts
src/installer.ts
src/test/suite/Utils/DeployTestUtil.ts
src/test/suite/_completion/completion.java.test.ts
src/ui-test/utils/utils.ts

it will allow to have better information from where the log is coming

Improve existing console logs

---

src/ui-test/resources/SimpleProperty.java
src/ui-test/resources/SimpleProperty.xml
src/ui-test/resources/SimpleProperty.yaml
src/ui-test/resources/SimpleProperty.yml
src/ui-test/tests/property_mode.test.ts

- Add property mode test 
- Add SimpleProperty templates 
[FUSETOOLS2-1716](https://issues.redhat.com/browse/FUSETOOLS2-1716)

FUSETOOLS2-1716: Add property mode test

---

.github/workflows/insider.yml
.github/workflows/main.yml

Same as https://github.com/camel-tooling/camel-dap-client-vscode/pull/520
[1] [FUSETOOLS2-2242](https://issues.redhat.com/browse/FUSETOOLS2-2242)

FUSETOOLS2-2242: Collect ui-tests screenshoots and logs when cancelled

---

.github/workflows/OtherOSes.yml
.github/workflows/insider.yml
.github/workflows/main.yml

it is no more a requirement since upgrade to Camel 4 and JBang fro Java support

Remove Maven from CI
